env = Environment()
env.Append( CPPPATH=['include'] )
#env.Append( CFLAGS=['-Weverything','-g'] )
#env.Append( CFLAGS=['-Weverything','-Wno-documentation','-g'] )
#env.Append( CFLAGS=['-Wall','-g','--coverage'] )
#env.Append( LINKFLAGS=['-g','--coverage'] )
env.Append( CFLAGS=['-Wall','-Wmissing-field-initializers','-Wmissing-variable-declarations','-g'] )
env.Append( LINKFLAGS=['-g'] )
src = ( Glob('src/*.c') )
lib = env.Library('simplemagic', src)

